name: Update data

on:
  schedule:
    - cron: '0 13 * * *'

jobs:
  download_push:
    name: Download and push data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Download data
        run: |
          curl -L --compressed -o src/data.json "https://interactive.zeit.de/cronjobs/2020/corona/impfzahlenAutomatisch.json"

      - name: Push data to GitHub
        env:
          GIT_AUTHOR_NAME: ffflorian
          GIT_AUTHOR_EMAIL: ffflorian@users.noreply.github.com
          GIT_COMMITTER_NAME: ffflorian
          GIT_COMMITTER_EMAIL: ffflorian@users.noreply.github.com
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global "user.email" "${GIT_AUTHOR_EMAIL}"
          git config --global "user.name" "${GIT_AUTHOR_NAME}"
          REPO_URL="$(git remote get-url origin | sed -n "s/https:\/\/github.com\//https:\/\/${GIT_AUTHOR_NAME}:${GITHUB_TOKEN}@github.com\//p")"
          git remote set-url origin "${REPO_URL}"
          git checkout main
          git add src/data.json
          git diff-index --quiet HEAD || git commit -m "chore: Update data"
          git push

      - name: Trigger page build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          event-type: trigger_build
