name: 'Update data'

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 18 * * *'

jobs:
  download_data:
    name: Download data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Push data to GitHub
        env:
          GIT_AUTHOR_NAME: ffflorian
          GIT_AUTHOR_EMAIL: ffflorian@users.noreply.github.com
          GIT_COMMITTER_NAME: ffflorian
          GIT_COMMITTER_EMAIL: ffflorian@users.noreply.github.com
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global "user.email" "${GIT_AUTHOR_EMAIL}"
          git config --global "user.name" "${GIT_AUTHOR_NAME}"
          REPO_URL="$(git remote get-url origin | sed -n "s/https:\/\/github.com\//https:\/\/${GIT_AUTHOR_NAME}:${GITHUB_TOKEN}@github.com\//p")"
          git remote set-url origin "${REPO_URL}"
          git checkout main
          ./update.sh
          git add src/data.json
          git commit -m "chore: Update data"
          git push
